spring:
  application:
    name: Edu-Tracking-System
# DATASOURCE CONFIGURATION

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        format_sql: true


#MAIL CONFIGURATION
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
  # EH CACHE CONFIGURATION
  cache:
    jcache:
      config: "classpath:ehcache.xml"
# APPLICATION CONFIGURATION
super_admin:
  email: ${SUPER_ADMIN_EMAIL}

